[package]
name = "doom-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bon = "3.3.2"

[dependencies.sdl2]
version = "0.37.0"
default-features = false
features = ["gfx", "ttf"]
